## General Plugin Configuration ##
# Do you want to use an economy plugin? If so, install vault and set this to "true" (Without qoutes)
vault: false

# If vault is set to true, then you can set the prices for the gadgets here.
Gadget_Prices:
    # 0 will be classed as "Free"
    # The price of the gadget will be added to the item's lore automatically. If you want to change the message, you can find
    # it in the messages.yml file.
    horseGadget: 0
    paintballGadget: 0
    mobcannonGadget: 0
    disguiseGadget: 0

# In which worlds will players receive the Gadget Selector gadget upon login?
# You should put your hub worlds in this setting. Delete the original list if you want to; it's just an example.
# If you want gadgets to be usable in all worlds, set it to an empty list e.g. guiGadgetWorlds: []
# Example configuration:
# guiGadgetWorlds:
# - Spawn
# - Hub
guiGadgetWorlds: []

# Do you want the players to be able to drop their gadgets?
# If you do, set this to 'true'.
allowDropping: false

# In which slot in the player's hotbar should the Gadget Selector be placed? (5 is the middle)
guiGadgetSlot: 5

# In which slot in the player's hotbar should the other Gadgets be placed ( default = 6 )
gadgetSlot: 6

## Disguise Gadget Settings ##
# This is a list of mobs that the players can disguise as (Look below for a list of mobs)
Disguises_List:
- BAT
- BLAZE
- CAVE_SPIDER
- CHICKEN
- COW
- CREEPER
- ENDERMAN
- HORSE
- IRON_GOLEM
- MOOSHROOM
- OCELOT
- PIG
- SHEEP
- SILVERFISH
- SKELETON
- SNOWMAN
- SPIDER
- ZOMBIE_PIG
- GUARDIAN
- ENDERMITE
- POLAR_BEAR

### Available mobs
# ZOMBIE, WITHER_SKELETON, SKELETON, ZOMBIE_PIG, BLAZE
# ENDERMAN, CREEPER, SPIDER, WITCH, WITHER_BOSS, GHAST
# GIANT, SLIME, CAVE_SPIDER, SILVERFISH, MAGMA_CUBE
# BAT, PIG, SHEEP, COW, CHICKEN, SQUID, WOLF, OCELOT
# HORSE, VILLAGER, IRON_GOLEM, SNOWMAN, ENDER_DRAGON
# MOOSHROOM, GUARDIAN, ENDERMITE, RABBIT, POLAR_BEAR

# Enabling this means the plugin will use all of the mobs above except for
# the ones you list in the blacklist below.
# Setting this to false means you'll have to individually list off the mobs
# and their alternate names in the later settings.
simpleBlacklist: true

# Which of the mobs above should be impossible to use?
# If simpleBlacklist is set to false, this will still override the mobs you
# have listed in the next setting. If you want mobs listed farther down to
# be usable, be sure that they're not present in this list.
blacklist:
- GIANT

# Alternate names for creatures. List them off in the pattern shown below.
# If you want the default name for a mob to be the only option, you must
# fill in that default name, however redundant it may look.
# Here are some examples, keep them if you want to.
OCELOT:
- cat
PIG:
- pig
